stages:
  - lint

variables:
  PIP_CACHE_DIR: .cache/pip

lint-job:
  stage: lint
  image: python:3.14-alpine
  before_script:
    - pip install --upgrade pip
    - pip install ruff
  script:
    - ruff check ./app/src
  cache:
    key: pip-cache
    paths:
      - .cache/pip
    policy: pull-push
  allow_failure: true
