services:
  nginx:
    container_name: logos_nginx
    image: nginx:1.29-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

  app:
    container_name: logos_app
    image: logos_app_image
    env_file: .env
    build: 
      context: .
      dockerfile: app/Dockerfile
    stdin_open: true
    tty: true

  database:
    container_name: logos_db
    image: postgres:16.10-alpine3.21
    env_file: .env

